"""empty message

Revision ID: 14e244d91be5
Revises: 6bc4eec5c212
Create Date: 2019-10-09 11:26:42.039012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14e244d91be5'
down_revision = '6bc4eec5c212'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('preferred_language', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'preferred_language')
    # ### end Alembic commands ###
