"""empty message

Revision ID: 6cd41955eae9
Revises: 046511fdd58d
Create Date: 2019-11-28 18:38:39.898052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cd41955eae9'
down_revision = '046511fdd58d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_org_level_account', 'organisation', 'transfer_account', ['org_level_transfer_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_org_level_account', 'organisation', type_='foreignkey')
    # ### end Alembic commands ###
