"""empty message

Revision ID: 886fc228858e
Revises: 14e244d91be5
Create Date: 2019-10-09 15:20:08.436050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '886fc228858e'
down_revision = '14e244d91be5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('user', sa.Column('gender', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'gender')
    op.drop_column('user', 'bio')
    # ### end Alembic commands ###
